linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - gofmt
    - govet
    - misspell
    - ineffassign
    - unused
    - typecheck
    - gocyclo
    - lll
    - goconst
    - gosimple
    - staticcheck
  disable:
    - errcheck # Too noisy for now

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - lll
    - path: test/
      linters:
        - gocyclo
        - lll
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
