// Symbol constants for the application

export interface Symbol {
  symbol: string
  name: string
}

export const SP500_SYMBOLS: Symbol[] = [
  // S&P 500 symbols
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
  { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.' },
  { symbol: 'META', name: 'Meta Platforms, Inc.' },
  { symbol: 'TSLA', name: 'Tesla, Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B' },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'MA', name: 'Mastercard Incorporated' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'PG', name: 'The Procter & Gamble Company' },
  { symbol: 'HD', name: 'The Home Depot, Inc.' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'MRK', name: 'Merck & Co., Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'MCD', name: 'McDonald’s Corporation' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'BAC', name: 'Bank of America Corporation' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'NEE', name: 'NextEra Energy, Inc.' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'UPS', name: 'United Parcel Service, Inc.' },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'LOW', name: 'Lowe’s Companies, Inc.' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation' },
  { symbol: 'BLK', name: 'BlackRock, Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical, Inc.' },
  { symbol: 'ELV', name: 'Elevance Health, Inc.' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.' },
  { symbol: 'PLD', name: 'Prologis, Inc.' },
  { symbol: 'NOW', name: 'ServiceNow, Inc.' },
  { symbol: 'MDLZ', name: 'Mondelez International, Inc.' },
  { symbol: 'CB', name: 'Chubb Limited' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
  { symbol: 'SYK', name: 'Stryker Corporation' },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals, Inc.' },
  { symbol: 'MU', name: 'Micron Technology, Inc.' },
  { symbol: 'FISV', name: 'Fiserv, Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences, Inc.' },
  { symbol: 'HUM', name: 'Humana Inc.' },
  { symbol: 'ADP', name: 'Automatic Data Processing, Inc.' },
  { symbol: 'PGR', name: 'The Progressive Corporation' },
  { symbol: 'ZTS', name: 'Zoetis Inc.' },
  { symbol: 'MO', name: 'Altria Group, Inc.' },
  { symbol: 'CSX', name: 'CSX Corporation' },
  { symbol: 'FDX', name: 'FedEx Corporation' },
  { symbol: 'EOG', name: 'EOG Resources, Inc.' },
  { symbol: 'GM', name: 'General Motors Company' },
  { symbol: 'KHC', name: 'The Kraft Heinz Company' },
  { symbol: 'MAR', name: 'Marriott International, Inc.' },
  { symbol: 'AON', name: 'Aon plc' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'EXC', name: 'Exelon Corporation' },
  { symbol: 'CME', name: 'CME Group Inc.' },
  { symbol: 'D', name: 'Dominion Energy, Inc.' },
  { symbol: 'AIG', name: 'American International Group, Inc.' },
  { symbol: 'COF', name: 'Capital One Financial Corporation' },
  { symbol: 'STZ', name: 'Constellation Brands, Inc.' },
  { symbol: 'MTB', name: 'M&T Bank Corporation' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance, Inc.' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'HCA', name: 'HCA Healthcare, Inc.' },
  { symbol: 'VLO', name: 'Valero Energy Corporation' },
  { symbol: 'ETN', name: 'Eaton Corporation plc' },
  { symbol: 'ROST', name: 'Ross Stores, Inc.' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
  { symbol: 'MCK', name: 'McKesson Corporation' },
  { symbol: 'ALL', name: 'The Allstate Corporation' },
  { symbol: 'TDG', name: 'TransDigm Group Incorporated' },
  { symbol: 'CDNS', name: 'Cadence Design Systems, Inc.' },
  { symbol: 'KLAC', name: 'KLA Corporation' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line, Inc.' },
  { symbol: 'PCAR', name: 'PACCAR Inc.' },
  { symbol: 'POOL', name: 'Pool Corporation' },
  { symbol: 'PAYX', name: 'Paychex, Inc.' },
  { symbol: 'STE', name: 'STERIS plc' },
  { symbol: 'WST', name: 'West Pharmaceutical Services, Inc.' },
  { symbol: 'TSCO', name: 'Tractor Supply Company' },
  { symbol: 'CARR', name: 'Carrier Global Corporation' },
  { symbol: 'FTNT', name: 'Fortinet, Inc.' },
  { symbol: 'DXCM', name: 'DexCom, Inc.' },
  { symbol: 'FICO', name: 'Fair Isaac Corporation' },
  { symbol: 'NUE', name: 'Nucor Corporation' },
  { symbol: 'VRSK', name: 'Verisk Analytics, Inc.' },
  { symbol: 'KEYS', name: 'Keysight Technologies, Inc.' },
  { symbol: 'TYL', name: 'Tyler Technologies, Inc.' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems, Inc.' },
  { symbol: 'TECH', name: 'Bio-Techne Corporation' },
  { symbol: 'ENPH', name: 'Enphase Energy, Inc.' },
  { symbol: 'GNRC', name: 'Generac Holdings Inc.' },
  { symbol: 'CF', name: 'CF Industries Holdings, Inc.' },
  { symbol: 'BALL', name: 'Ball Corporation' },
  { symbol: 'HES', name: 'Hess Corporation' },
  { symbol: 'CHD', name: 'Church & Dwight Co., Inc.' },
  { symbol: 'GPC', name: 'Genuine Parts Company' },
  { symbol: 'BRO', name: 'Brown & Brown, Inc.' },
  { symbol: 'AFL', name: 'Aflac Incorporated' },
  { symbol: 'RMD', name: 'ResMed Inc.' },
  { symbol: 'EXR', name: 'Extra Space Storage Inc.' },
  { symbol: 'VTRS', name: 'Viatris Inc.' },
  { symbol: 'CNP', name: 'CenterPoint Energy, Inc.' },
  { symbol: 'AES', name: 'The AES Corporation' },
  { symbol: 'NRG', name: 'NRG Energy, Inc.' },
  { symbol: 'APA', name: 'APA Corporation' },
  { symbol: 'FANG', name: 'Diamondback Energy, Inc.' },
  { symbol: 'EQT', name: 'EQT Corporation' },
  { symbol: 'MRO', name: 'Marathon Oil Corporation' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation' },
  { symbol: 'HAL', name: 'Halliburton Company' },
  { symbol: 'BKR', name: 'Baker Hughes Company' },
  { symbol: 'SLB', name: 'Schlumberger Limited' },
  { symbol: 'VMC', name: 'Vulcan Materials Company' },
  { symbol: 'MLM', name: 'Martin Marietta Materials, Inc.' },
  { symbol: 'WY', name: 'Weyerhaeuser Company' },
  { symbol: 'IP', name: 'International Paper Company' },
  { symbol: 'PKG', name: 'Packaging Corporation of America' },
  { symbol: 'WRK', name: 'WestRock Company' },
  { symbol: 'CE', name: 'Celanese Corporation' },
  { symbol: 'EMN', name: 'Eastman Chemical Company' },
  { symbol: 'PPG', name: 'PPG Industries, Inc.' },
  { symbol: 'SHW', name: 'The Sherwin-Williams Company' },
  { symbol: 'DD', name: 'DuPont de Nemours, Inc.' },
  { symbol: 'DOW', name: 'Dow Inc.' },
  { symbol: 'CTVA', name: 'Corteva, Inc.' },
  { symbol: 'MOS', name: 'The Mosaic Company' },
  { symbol: 'NEM', name: 'Newmont Corporation' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.' },
  { symbol: 'GOLD', name: 'Barrick Gold Corporation' },
  { symbol: 'RGLD', name: 'Royal Gold, Inc.' },
  { symbol: 'AEM', name: 'Agnico Eagle Mines Limited' },
  { symbol: 'WPM', name: 'Wheaton Precious Metals Corp.' },
  { symbol: 'NTRS', name: 'Northern Trust Corporation' },
  { symbol: 'STT', name: 'State Street Corporation' },
  { symbol: 'BK', name: 'The Bank of New York Mellon Corporation' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'PNC', name: 'The PNC Financial Services Group, Inc.' },
  { symbol: 'TFC', name: 'Truist Financial Corporation' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Incorporated' },
  { symbol: 'KEY', name: 'KeyCorp' },
  { symbol: 'RF', name: 'Regions Financial Corporation' },
  { symbol: 'CMA', name: 'Comerica Incorporated' },
  { symbol: 'ZION', name: 'Zions Bancorporation, National Association' },
  { symbol: 'SIVB', name: 'SVB Financial Group' },
  { symbol: 'FRC', name: 'First Republic Bank' },
  { symbol: 'MTB', name: 'M&T Bank Corporation' },
  { symbol: 'CFG', name: 'Citizens Financial Group, Inc.' },
  { symbol: 'HWC', name: 'Hancock Whitney Corporation' },
  { symbol: 'BOKF', name: 'BOK Financial Corporation' },
  { symbol: 'SNV', name: 'Synovus Financial Corp.' },
  { symbol: 'UCBI', name: 'United Community Banks, Inc.' },
  { symbol: 'FULT', name: 'Fulton Financial Corporation' },
  { symbol: 'TCBI', name: 'Texas Capital Bancshares, Inc.' },
  { symbol: 'PB', name: 'Prosperity Bancshares, Inc.' },
  { symbol: 'CFR', name: 'Cullen/Frost Bankers, Inc.' },
  { symbol: 'BOH', name: 'Bank of Hawaii Corporation' },
]

export const OTHER_SYMBOLS: Symbol[] = [
  { symbol: 'ON', name: 'ON Holdings AG' },
  { symbol: 'PL', name: 'Planet Labs PBC' },
  { symbol: 'OSCR', name: 'Oscar Health, Inc.' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor Manufacturing Company Limited' },
]

export const SYMBOLS: Symbol[] = [...SP500_SYMBOLS, ...OTHER_SYMBOLS]
